### ISSUE TITLE
export markdown

### ISSUE THREAD

**Issue by ArneNostitz** [metawops/obsidian-table-to-csv-export#10]
hi, is this still in development?

i am trying to get obsidian files into an online database tool. and i need the full content of a note in a cell, inluding the markdown and all the formatting in tact. 

any way of doin an export without all these things getting stripped from the dataview table?

(i am using dataviewjs to get the file data ... and that works great)

**Comment by metawops** [comment]
Hi @ArneNostitz,
tbh, this would be way beyond the scope of my plugin. Plus, I haven't found the time to work on it for a very long time and probably won't be able to work on it in the near future. 🤷‍♂️
