### ISSUE TITLE
It seems that Chinese document export is not supported?

### ISSUE THREAD

**Issue by chenxin0397** [metawops/obsidian-table-to-csv-export#5]
My table export appears garbled

**Comment by metawops** [comment]
If you have a Chinese Markdown document for me I could try and test what might be the problem.
I need more details. What's your original input Markdown document? How does the document look in rendered preview mode in Obsidian? How does your exported CSV file look?

**Comment by chenxin0397** [comment]
**preview mode in Obsidian**
![image](https://user-images.githubusercontent.com/73974352/198185661-8664c1a6-712b-4e44-9b5b-4f804b2dd057.png)

---

**this is the code i use**
```dataview
table without id
状态,
类型,
file.link as 文件,
Pid as ID, 
日期,
功能介绍
from #插件记录
where !contains(file.name, "模板-插件记录")
sort 日期 desc
```
------

**This is the monitored file**

- ! 填完了别保存！！！！

状态:: 已安装
Pid:: url-into-selection
类型:: 链接
日期:: 2022-10-27
tags:: #插件记录
作者:: denolehov
安装版本:: 
功能介绍:: 将剪贴的地址 贴入文字 生成链接
aliases:: 文字改链接
仓库网址:: 
删除原因:: 
我的评价:: ⭐⭐⭐⭐⭐

## 仓库介绍

## 命令

-----
**exported CSV file look like this**
![image](https://user-images.githubusercontent.com/73974352/198186369-e77d2d36-0cd0-420e-9c9c-615135ad5a5f.png)

**Comment by metawops** [comment]
I'll look into it – but be patient, it'll take some time!

**Comment by gouxuenan** [comment]
应该是csv编码的问题，我在mac上面导出中文csv一切正常。
It should be a csv encoding problem. I exported Chinese csv on the mac and everything is normal.

**Comment by chenxin0397** [comment]
> 应该是csv编码的问题，我在mac上面导出中文csv一切正常。 It should be a csv encoding problem. I exported Chinese csv on the mac and everything is normal.

我用的是widows，请问有办法调整吗？

**Comment by metawops** [comment]
Please report back if this solves your problem, @chenxin0397, so that we can close this issue here. 
And thanks for your help, @gouxuenan!
🙏
